services:
  local:
    image: ruby:3.1
    profiles: ["local"]
    working_dir: /srv/jekyll
    volumes:
      - .:/srv/jekyll
      - bundle_cache:/usr/local/bundle
    ports:
      - "4000:4000"
    command: bash -c "bundle install && bundle exec jekyll serve --host 0.0.0.0 --watch --force_polling --config _config-local.yml"

  build:
    image: ruby:3.1
    profiles: ["build"]
    working_dir: /srv/jekyll
    volumes:
      - .:/srv/jekyll
      - bundle_cache:/usr/local/bundle
    command: bash -c "bundle install && bundle exec jekyll build"

volumes:
  bundle_cache:
    driver: local
